### PR TITLE
Views changed to make notebook less cluttered, pep-8 cleaning

### PR DESCRIPTION
**Pull request by sysadminmatmoz**
Views were changed to give a form like this:
screen_109

Tabs are nested under the Other info tab to free tab space on task form, which was already cluttered as it is.

### CODE REVIEW

**Comment by Nick-OpusVL** [comment]
Hi, Matjaz.

If you closed this because I haven't got back to you, I apologise for not getting back sooner.  Your work is an excellent candidate for inclusion, and thankyou for taking the time to do it, it's just recently I've had a lot of other tasks which have have been taking precedence.  As soon as I get a chance I'll do some sanity tests and assuming they come out rosy I'll merge your work.

Thanks again,

Nick

**Comment by Nick-OpusVL** [comment]
I notice your repository or branch is now gone.  I've recovered most of the work from 12.patch, minus the deletion of .gitignore and README.md, and put it in branch pull-12 of this repository.

The code mostly looks fine, and it all upgrades OK.  I'll still want to check with my colleagues that the UI changes are OK to go ahead with in case users get upset that things change under them...

**Comment by Nick-OpusVL** [comment]
Hi Matjaz.

Your UI changes were accepted when I spoke to my colleagues just now.

I've applied your patch to the 8.0 branch.

Here is the commit in question:
https://github.com/OpusVL/odoo-project-management/commit/97ac8dbfddee85d06a4ae284c04afbed5349d82e

Thank you for your contribution.

Nick

**Comment by sysadminmatmoz** [comment]
Hi Nick.
Sorry, I didn't notice the discussion in my way too cluttered inbox.

The repo didn't disappear, it was moved here: https://github.com/projectexpert/pmis

I joined forces with Jordi, so lot of work was done.

**Pull request closed without merging**
